Add error handlings and minor improvements.

diff --git a/bin/app-template-py b/bin/app-template-py
--- a/bin/app-template-py
+++ b/bin/app-template-py
@@ -58,11 +58,13 @@ mv * .* .original-files/ 2> /dev/null
 # Create files from template.
 echo -e "\e[1;37mCopying template files…\e[0m"
 cp -r $TEMPLATE_DIR/. .
+rm README.md
 find . -name .gitkeep -delete
 
 # Create virtual environment.
 echo -e "\e[1;37mCreating virtual environment…\e[0m"
 $PY_EXEC -m venv venv
+[ $? = 0 ] || { echo -e "\e[31mERROR: Virtual environment creation failed.\e[0m"; exit 1; }
 
 # Update configuration files.
 sed -i "s#%HOME%#$HOME#g;s/%APP_NAME%/$APP_NAME/g;s/%APP_PORT%/$APP_PORT/" uwsgi.ini
diff --git a/bin/py-install-version b/bin/py-install-version
--- a/bin/py-install-version
+++ b/bin/py-install-version
@@ -35,6 +35,7 @@ export TMPDIR=$HOME/tmp
 cd $TMPDIR
 echo -e "\e[1;37mDownloading sources…\e[0m"
 wget https://www.python.org/ftp/python/$PY_VERSION/Python-$PY_VERSION.tgz
+[ $? = 0 ] || { echo -e "\e[31mERROR: Downloading sources failed.\e[0m"; exit 1; }
 tar zxvf Python-$PY_VERSION.tgz
 
 cd Python-$PY_VERSION
@@ -50,5 +51,6 @@ rm -rf Python-${PY_VERSION}*
 
 # Execution report.
 py_exec=`pyWhichExec $PY_VERSION`
+[ -z "$py_exec" ] && { echo -e "\e[31mERROR: Python $PY_VERSION executable not found.\e[0m"; exit 1; }
 echo -e "\n\e[32mSuccessfully installed Python `pyRealVersion $py_exec` ($py_exec).\e[0m"
 echo
